// ── Sensitivity Label Script Builder ─────────────────────────────────────────
// Generates 03_Sensitivity_Labels_-_Deployment_Commands.ps1
// Uses: New-Label (4 labels, no policy/publishing — done manually in portal)
//
// KEY FIX: New-Label does NOT use splatted hashtables reliably for marking
// parameters when some are disabled. We generate explicit -Parameter Value
// arguments per-label instead, omitting disabled marking parameters entirely.
// The cmdlet interprets absence of a marking parameter as "disabled" — passing
// -ApplyContentMarkingFooterEnabled $false alongside other footer params causes
// TextEmptyException. Solution: only include marking params when enabled.

export function downloadText(content, filename, mime = 'text/plain') {
  const blob = new Blob([content], { type: mime })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href = url; a.download = filename; a.click()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

function psStr(s) { return String(s).replace(/"/g, '""') }
function hexColor(s) {
  const c = String(s).trim()
  return c.startsWith('#') ? c : '#' + c
}

// Build a New-Label call with only the parameters that are actually needed.
// Disabled markings are simply omitted — not passed as $false.
function buildNewLabelCall(label) {
  const L = []

  // Required parameters
  L.push(`New-Label \``)
  L.push(`    -Name        "${psStr(label.name)}" \``)
  L.push(`    -DisplayName "${psStr(label.displayName)}" \``)
  L.push(`    -Tooltip     "${psStr(label.tooltip)}" \``)
  L.push(`    -ContentType "File, Email" \``)

  // Footer — only include if enabled AND has text
  if (label.footer.enabled && label.footer.text.trim()) {
    L.push(`    -ApplyContentMarkingFooterEnabled   $true \``)
    L.push(`    -ApplyContentMarkingFooterText      "${psStr(label.footer.text)}" \``)
    L.push(`    -ApplyContentMarkingFooterFontColor "${hexColor(label.footer.color)}" \``)
    L.push(`    -ApplyContentMarkingFooterFontSize  ${label.footer.size} \``)
    L.push(`    -ApplyContentMarkingFooterAlignment "${label.footer.align}" \``)
    L.push(`    -ApplyContentMarkingFooterMargin    15 \``)
  }

  // Header — only include if enabled AND has text
  if (label.header.enabled && label.header.text.trim()) {
    L.push(`    -ApplyContentMarkingHeaderEnabled   $true \``)
    L.push(`    -ApplyContentMarkingHeaderText      "${psStr(label.header.text)}" \``)
    L.push(`    -ApplyContentMarkingHeaderFontColor "${hexColor(label.header.color)}" \``)
    L.push(`    -ApplyContentMarkingHeaderFontSize  ${label.header.size} \``)
    L.push(`    -ApplyContentMarkingHeaderAlignment "${label.header.align}" \``)
    L.push(`    -ApplyContentMarkingHeaderMargin    15 \``)
  }

  // Watermark — only include if enabled AND has text
  if (label.watermark.enabled && label.watermark.text.trim()) {
    L.push(`    -ApplyWaterMarkingEnabled   $true \``)
    L.push(`    -ApplyWaterMarkingText      "${psStr(label.watermark.text)}" \``)
    L.push(`    -ApplyWaterMarkingLayout    "${label.watermark.layout}" \``)
    L.push(`    -ApplyWaterMarkingFontSize  ${label.watermark.size} \``)
    L.push(`    -ApplyWaterMarkingFontColor "${hexColor(label.footer.color)}" \``)
  }

  // Label colour via AdvancedSettings — always set
  if (label.color) {
    L.push(`    -AdvancedSettings @{color="${hexColor(label.color)}"}`)
  } else {
    // Remove trailing backtick-space from last param line
    const last = L.pop()
    L.push(last.replace(/ \`$/, ''))
  }

  return L.join('\n')
}

export function buildLabelScript(labels, adminUPN, orgName) {
  const upn = adminUPN || 'admin@yourtenant.onmicrosoft.com'

  const lines = []

  lines.push(`#Requires -Modules ExchangeOnlineManagement`)
  lines.push(`#------------------------------------------------------------------------------`)
  lines.push(`# Script 3 of 3: Deploy Sensitivity Labels`)
  lines.push(`# Generated by: BUI Purview Deployment Script Generator`)
  lines.push(`#`)
  lines.push(`# WHAT THIS SCRIPT DOES:`)
  lines.push(`#   Creates ${labels.length} sensitivity labels in Microsoft Purview.`)
  lines.push(`#   Labels are created but NOT published — a label policy must be`)
  lines.push(`#   created separately in the Purview portal once your pilot group`)
  lines.push(`#   is confirmed.`)
  lines.push(`#`)
  lines.push(`# ENCRYPTION:`)
  lines.push(`#   Encryption is NOT configured by this script. Per the BUI Purview`)
  lines.push(`#   Maturity Framework, encryption (Azure RMS / Microsoft Purview`)
  lines.push(`#   Information Protection) is introduced in Phase 06 of the Sensitivity`)
  lines.push(`#   Labelling track — after mandatory labelling is stable and the customer`)
  lines.push(`#   has confirmed which labels should be encrypted. Encryption will be`)
  lines.push(`#   configured manually during the relevant phase of the engagement.`)
  lines.push(`#   Requires: Purview Suite add-on / M365 E5.`)
  lines.push(`#`)
  lines.push(`# WHAT THIS SCRIPT DOES NOT DO:`)
  lines.push(`#   Does NOT create a label policy or publish labels to any users.`)
  lines.push(`#   Does NOT configure encryption (see note above).`)
  lines.push(`#   A commented-out New-LabelPolicy example is included at the bottom`)
  lines.push(`#   of this script for reference once the pilot group is confirmed.`)
  lines.push(`#`)
  lines.push(`# AFTER RUNNING THIS SCRIPT:`)
  lines.push(`#   1. Verify labels in Purview portal: https://purview.microsoft.com`)
  lines.push(`#      Information Protection > Labels`)
  lines.push(`#   2. Confirm pilot group with customer`)
  lines.push(`#   3. Create and publish label policy via the portal or run the`)
  lines.push(`#      commented-out New-LabelPolicy block at the bottom of this script`)
  lines.push(`#`)
  lines.push(`# LABELS IN THIS DEPLOYMENT (${labels.length}):`)
  labels.forEach(l => lines.push(`#   - ${l.displayName}`))
  lines.push(`#`)
  lines.push(`# REQUIRED ROLE: Compliance Administrator`)
  lines.push(`#------------------------------------------------------------------------------`)
  lines.push(``)
  lines.push(`$AdminUPN = "${psStr(upn)}"`)
  lines.push(``)
  lines.push(`#------------------------------------------------------------------------------`)
  lines.push(`# CONNECT`)
  lines.push(`#------------------------------------------------------------------------------`)
  lines.push(`Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force`)
  lines.push(``)
  lines.push(`if (-not (Get-Module -ListAvailable -Name ExchangeOnlineManagement)) {`)
  lines.push(`    Write-Host "Installing ExchangeOnlineManagement module..." -ForegroundColor Yellow`)
  lines.push(`    Install-Module -Name ExchangeOnlineManagement -Force -Scope CurrentUser`)
  lines.push(`}`)
  lines.push(``)
  lines.push(`Import-Module ExchangeOnlineManagement`)
  lines.push(`Connect-IPPSSession -UserPrincipalName $AdminUPN`)
  lines.push(``)
  lines.push(`#------------------------------------------------------------------------------`)
  lines.push(`# CREATE SENSITIVITY LABELS`)
  lines.push(`#`)
  lines.push(`# ContentType "File, Email" makes all labels compatible with future`)
  lines.push(`# sub-label promotion. Purview automatically treats a label as a parent`)
  lines.push(`# when a child label is added beneath it — no script changes required.`)
  lines.push(`#`)
  lines.push(`# Marking parameters are ONLY included when the marking is enabled.`)
  lines.push(`# Passing disabled marking parameters (e.g. -ApplyContentMarkingFooterEnabled`)
  lines.push(`# $false alongside other footer params) causes TextEmptyException in Purview.`)
  lines.push(`#------------------------------------------------------------------------------`)

  labels.forEach((label, idx) => {
    lines.push(``)
    lines.push(`# ── Label ${idx + 1} of ${labels.length}: ${label.displayName} ──`)
    lines.push(`Write-Host "Creating label: ${label.displayName}..." -NoNewline`)
    lines.push(``)
    lines.push(`if (Get-Label -Identity "${psStr(label.name)}" -ErrorAction SilentlyContinue) {`)
    lines.push(`    Write-Host " [ALREADY EXISTS — skipping]" -ForegroundColor Yellow`)
    lines.push(`} else {`)
    lines.push(`    try {`)

    // Build the New-Label call — indent it inside the try block
    const callLines = buildNewLabelCall(label).split('\n')
    callLines.forEach((l, i) => {
      const indent = i === 0 ? '        ' : '        '
      lines.push(`${indent}${l}`)
    })

    lines.push(`        Write-Host " [OK]" -ForegroundColor Green`)
    lines.push(`    } catch {`)
    lines.push(`        Write-Host " [FAIL] $_" -ForegroundColor Red`)
    lines.push(`    }`)
    lines.push(`}`)
  })

  lines.push(``)
  lines.push(`#------------------------------------------------------------------------------`)
  lines.push(`# VERIFY`)
  lines.push(`#------------------------------------------------------------------------------`)
  lines.push(`Write-Host ""`)
  lines.push(`Write-Host "========================================" -ForegroundColor Cyan`)
  lines.push(`Write-Host " Label deployment complete. Verifying..." -ForegroundColor Cyan`)
  lines.push(`Write-Host "========================================" -ForegroundColor Cyan`)
  lines.push(`Write-Host ""`)
  lines.push(``)
  lines.push(`$verifiedCount = 0`)

  labels.forEach(label => {
    lines.push(`$lbl = Get-Label -Identity "${psStr(label.name)}" -ErrorAction SilentlyContinue`)
    lines.push(`if ($lbl) {`)
    lines.push(`    Write-Host "  [OK]  ${label.displayName} (GUID: $($lbl.Guid))" -ForegroundColor Green`)
    lines.push(`    $verifiedCount++`)
    lines.push(`} else {`)
    lines.push(`    Write-Host "  [MISSING] ${label.displayName}" -ForegroundColor Red`)
    lines.push(`}`)
  })

  lines.push(``)
  lines.push(`Write-Host ""`)
  lines.push(`Write-Host "  $verifiedCount of ${labels.length} labels verified." -ForegroundColor Cyan`)
  lines.push(`Write-Host ""`)
  lines.push(`Write-Host "NEXT STEPS:" -ForegroundColor Yellow`)
  lines.push(`Write-Host "  1. Review labels in Purview portal: https://purview.microsoft.com" -ForegroundColor Gray`)
  lines.push(`Write-Host "     Information Protection > Labels" -ForegroundColor Gray`)
  lines.push(`Write-Host "  2. Confirm pilot group with customer (security group or specific users)" -ForegroundColor Gray`)
  lines.push(`Write-Host "  3. Create a label policy to publish labels - see commented block below" -ForegroundColor Gray`)
  lines.push(`Write-Host ""`)

  // Commented-out policy block
  lines.push(``)
  lines.push(`#------------------------------------------------------------------------------`)
  lines.push(`# LABEL POLICY — RUN MANUALLY ONCE PILOT GROUP IS CONFIRMED`)
  lines.push(`# Uncomment and update the parameters below, then run this block separately.`)
  lines.push(`#`)
  lines.push(`# KEY DECISIONS BEFORE RUNNING:`)
  lines.push(`#   -ExchangeLocation / -SharePointLocation / -OneDriveLocation`)
  lines.push(`#     Replace "All" with a specific security group email address`)
  lines.push(`#     when scoping to a pilot group, e.g. "purview-pilot@contoso.com"`)
  lines.push(`#   DefaultLabelId`)
  lines.push(`#     GUID of the label to apply by default. Recommend "General".`)
  lines.push(`#     Retrieved automatically from the deployed label below.`)
  lines.push(`#   MandatoryToLabel`)
  lines.push(`#     $true forces users to classify before saving/sending.`)
  lines.push(`#   JustificationRequiredForClassificationLowering`)
  lines.push(`#     $true requires users to justify when downgrading a label.`)
  lines.push(`#------------------------------------------------------------------------------`)
  lines.push(``)
  lines.push(`<#`)
  lines.push(``)

  const orgStr = orgName ? psStr(orgName) : 'Contoso'
  const labelNamesList = labels.map(l => `"${psStr(l.name)}"`).join(', ')

  lines.push(`$policyName = "${orgStr} - Sensitivity Label Policy"`)
  lines.push(``)
  lines.push(`# Get the GUID of the General label for use as the default label`)
  lines.push(`$generalLabel    = Get-Label -Identity "General" -ErrorAction SilentlyContinue`)
  lines.push(`$defaultLabelGuid = $generalLabel.Guid`)
  lines.push(``)
  lines.push(`New-LabelPolicy \``)
  lines.push(`    -Name               $policyName \``)
  lines.push(`    -Labels             ${labelNamesList} \``)
  lines.push(`    -ExchangeLocation   "All" \``)
  lines.push(`    -SharePointLocation "All" \``)
  lines.push(`    -OneDriveLocation   "All"`)
  lines.push(``)
  lines.push(`# Apply advanced policy settings`)
  lines.push(`Set-LabelPolicy -Identity $policyName -AdvancedSettings @{`)
  lines.push(`    DefaultLabelId                                 = $defaultLabelGuid`)
  lines.push(`    MandatoryToLabel                               = "True"`)
  lines.push(`    JustificationRequiredForClassificationLowering = "True"`)
  lines.push(`}`)
  lines.push(``)
  lines.push(`Write-Host "Label policy '$policyName' created and published." -ForegroundColor Green`)
  lines.push(`#>`)

  return lines.join('\n')
}
