import { SIT_XML } from '../data/sitXml.js'
import { POLICIES } from '../data/policies.js'
import { SILENT_PURVIEW_SITS } from '../data/sits.js'

// ── Helpers ──────────────────────────────────────────────────────────────────

export function sanitizeId(id) { return id.replace(/[^a-zA-Z0-9_]/g, '_') }
export function escXml(s) { return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;') }
export function generateGUID() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
    const r = Math.random() * 16 | 0
    return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16)
  })
}
export function downloadText(content, filename, mime = 'text/plain') {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = filename; a.click()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

// ── SIT helpers ──────────────────────────────────────────────────────────────

export function getEffectiveSitIds(policy, allSITs) {
  const core = new Set(policy.sitIds)
  allSITs.forEach(cs => { if (cs.isCustom && cs.group === policy.group) core.add(cs.id) })
  return [...core]
}

/**
 * Returns the full list of SITs that should be included in a policy's
 * AdvancedRule JSON for Script 2. This includes:
 *  1. Library SITs that are in the policy's sitIds AND have been selected in Step 1
 *  2. User-added custom SITs from the same group that are selected
 *  3. Extra built-in SITs added via the picker for this policy
 *  4. Silent built-in Purview SITs (credit_card, sa_id, sa_addresses) that the
 *     policy references — these are always included regardless of Step 1 selections
 *     because they live in Purview natively and don't need to be deployed.
 */
export function getEffectiveSITsForPolicy(policy, allSITs, selectedSITIds, policyExtraSITs = {}) {
  // Library SITs selected in Step 1
  const coreSITs = allSITs.filter(s => policy.sitIds.includes(s.id) && selectedSITIds.has(s.id))
  // User-added custom SITs from same group, selected in Step 1
  const customGroupSITs = allSITs.filter(s => s.isCustom && s.group === policy.group && selectedSITIds.has(s.id))
  // Extra built-in SITs added via the picker
  const extras = policyExtraSITs[policy.id] || []
  // Silent Purview built-ins that the policy references — always included
  const silentForPolicy = SILENT_PURVIEW_SITS.filter(s => policy.sitIds.includes(s.id))

  const seen = new Set()
  return [...coreSITs, ...customGroupSITs, ...extras, ...silentForPolicy].filter(s => {
    if (seen.has(s.guid)) return false
    seen.add(s.guid); return true
  })
}


// ── XML builder ──────────────────────────────────────────────────────────────

function buildCustomEntityBlock(s) {
  const rid = sanitizeId(s.id)
  const prox = s.proximity || 50
  const kwMatch = s.keywords?.length ? `\n        <Match idRef="Keywords_${rid}" />` : ''
  return `    <Version minEngineVersion="15.01.0998.000">
      <Entity id="${s.guid}"
              patternsProximity="${prox}" recommendedConfidence="75" relaxProximity="false">
        <Pattern confidenceLevel="75">
          <IdMatch idRef="Regex_${rid}" />${kwMatch}
        </Pattern>
      </Entity>
    </Version>`
}

function buildCustomKeywordBlock(s) {
  if (!s.keywords?.length) return ''
  const rid = sanitizeId(s.id)
  const terms = s.keywords.map(k => `        <Term>${escXml(k)}</Term>`).join('\n')
  return `    <Keyword id="Keywords_${rid}">
      <Group matchStyle="word">
${terms}
      </Group>
    </Keyword>`
}

export function buildXML(allSITs, selectedSITIds, tenantId) {
  const customNonBuiltIn = allSITs.filter(s => selectedSITIds.has(s.id) && !s.builtIn)
  if (customNonBuiltIn.length === 0) return null

  const publisherId = tenantId?.trim() || 'YOUR-TENANT-ID-HERE'

  const entityBlocks = customNonBuiltIn
    .map(s => s.isCustom ? buildCustomEntityBlock(s) : (SIT_XML[s.id]?.entityBlock || ''))
    .filter(Boolean).join('\n\n')

  const regexBlocks = customNonBuiltIn
    .map(s => s.isCustom
      ? `    <Regex id="Regex_${sanitizeId(s.id)}">${escXml(s.regex || '')}</Regex>`
      : (SIT_XML[s.id]?.regexBlock || ''))
    .filter(Boolean).join('\n')

  const keywordBlocks = customNonBuiltIn
    .map(s => s.isCustom ? buildCustomKeywordBlock(s) : (SIT_XML[s.id]?.keywordBlock || ''))
    .filter(Boolean).join('\n\n')

  const localizedBlocks = customNonBuiltIn.map(s => {
    const desc = s.isCustom ? `Custom SIT: ${s.name}` : (SIT_XML[s.id]?.localizedDesc || '')
    return `    <Resource idRef="${s.guid}">
      <Name default="true" langcode="en-us">${escXml(s.name)}</Name>
      <Description default="true" langcode="en-us">${escXml(desc)}</Description>
    </Resource>`
  }).join('\n\n')

  return `<?xml version="1.0" encoding="utf-16"?>
<!--
  BUI - Custom Sensitive Information Types
  Rule Package: BUI.SouthAfrica.CustomRulePack
  Generated by: BUI Purview Deployment Script Generator

  BEFORE DEPLOYING: The Publisher id below should be your Azure AD Tenant ID.
  ${publisherId === 'YOUR-TENANT-ID-HERE' ? 'Find it at: https://portal.azure.com/#view/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/~/Overview' : `Tenant ID: ${publisherId}`}

  SITs included (${customNonBuiltIn.length}):
${customNonBuiltIn.map(s => `  - ${s.name}`).join('\n')}
-->
<RulePackage xmlns="http://schemas.microsoft.com/office/2011/mce"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <RulePack id="DAD86A92-AB18-43BB-AB35-96F7C594ADBB">
    <Version build="0" major="1" minor="1" revision="0" />
    <Publisher id="${publisherId}" />
    <Details defaultLangCode="en-us">
      <LocalizedDetails langcode="en-us">
        <PublisherName>BUI</PublisherName>
        <Name>BUI.SouthAfrica.CustomRulePack</Name>
        <Description>Custom Sensitive Information Types: ${customNonBuiltIn.map(s => s.name).join(', ')}.</Description>
      </LocalizedDetails>
    </Details>
  </RulePack>
  <Rules>

    <!-- ENTITY DEFINITIONS -->
${entityBlocks}

    <!-- REGEX DEFINITIONS -->
${regexBlocks}

    <!-- KEYWORD DEFINITIONS -->
${keywordBlocks}

    <!-- LOCALISED DISPLAY NAMES -->
    <LocalizedStrings>
${localizedBlocks}
    </LocalizedStrings>
  </Rules>
</RulePackage>`
}

// ── Script 1: SIT deployment ─────────────────────────────────────────────────

export function buildScript1(allSITs, selectedSITIds, adminUPN) {
  const customNonBuiltIn = allSITs.filter(s => selectedSITIds.has(s.id) && !s.builtIn)
  if (customNonBuiltIn.length === 0) return null
  const upn = adminUPN?.trim() || 'admin@yourtenant.onmicrosoft.com'

  return `#Requires -Modules ExchangeOnlineManagement
#------------------------------------------------------------------------------
# Script 1 of 2: Deploy BUI Custom SA Sensitive Information Types
# Generated by: BUI Purview Deployment Script Generator
#
# BEFORE YOU RUN:
#   1. Open 01_SA_Custom_SITs_-_Rule_Package.xml
#   2. Confirm the Publisher id matches your Azure AD Tenant ID
#   3. Update $XmlPath to the file location on your machine
#   4. Account needs: Compliance Administrator + Security Administrator
#
# SITs in this deployment (${customNonBuiltIn.length}):
${customNonBuiltIn.map(s => `#   - ${s.name}`).join('\n')}
#------------------------------------------------------------------------------

$AdminUPN    = "${upn}"
$XmlPath     = "C:\\Path\\To\\01_SA_Custom_SITs_-_Rule_Package.xml"
$PackageName = "BUI.SouthAfrica.CustomRulePack"

$ExpectedSITs = @(
${customNonBuiltIn.map(s => `    "${s.name}"`).join(',\n')}
)

function Get-XmlBytesAsUtf16 {
    param ([string]$Path)
    $rawBytes = [System.IO.File]::ReadAllBytes($Path)
    if ($rawBytes.Length -ge 2 -and $rawBytes[0] -eq 0xFF -and $rawBytes[1] -eq 0xFE) {
        Write-Host "  XML: UTF-16 LE (no conversion)" -ForegroundColor Gray; return $rawBytes
    }
    if ($rawBytes.Length -ge 2 -and $rawBytes[0] -eq 0xFE -and $rawBytes[1] -eq 0xFF) {
        $content = [System.Text.Encoding]::BigEndianUnicode.GetString($rawBytes, 2, $rawBytes.Length - 2)
    } else {
        $offset = 0
        if ($rawBytes.Length -ge 3 -and $rawBytes[0] -eq 0xEF -and $rawBytes[1] -eq 0xBB -and $rawBytes[2] -eq 0xBF) { $offset = 3 }
        $content = [System.Text.Encoding]::UTF8.GetString($rawBytes, $offset, $rawBytes.Length - $offset)
    }
    $utf16Bytes = [System.Text.Encoding]::Unicode.GetBytes($content)
    $bom = [byte[]](0xFF, 0xFE)
    $final = New-Object byte[] ($bom.Length + $utf16Bytes.Length)
    [System.Buffer]::BlockCopy($bom, 0, $final, 0, $bom.Length)
    [System.Buffer]::BlockCopy($utf16Bytes, 0, $final, $bom.Length, $utf16Bytes.Length)
    return $final
}

Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
if (-not (Get-Module -ListAvailable -Name ExchangeOnlineManagement)) {
    Install-Module -Name ExchangeOnlineManagement -Force -Scope CurrentUser
}
Import-Module ExchangeOnlineManagement
Connect-IPPSSession -UserPrincipalName $AdminUPN

if (-not (Test-Path $XmlPath)) { Write-Host "ERROR: XML not found at: $XmlPath" -ForegroundColor Red; exit 1 }
$fileData = Get-XmlBytesAsUtf16 -Path $XmlPath
$existing = Get-DlpSensitiveInformationTypeRulePackage -Identity $PackageName -ErrorAction SilentlyContinue

if ($existing) {
    Write-Host "WARNING: Package '$PackageName' already exists." -ForegroundColor Yellow
    $choice = Read-Host "Update existing package? (Y / N)"
    if ($choice -in 'Y','y') {
        Set-DlpSensitiveInformationTypeRulePackage -FileData $fileData -ErrorAction Stop
        Write-Host "Package updated." -ForegroundColor Green
    } else { Write-Host "Aborted."; exit 0 }
} else {
    New-DlpSensitiveInformationTypeRulePackage -FileData $fileData -ErrorAction Stop
    Write-Host "Package deployed." -ForegroundColor Green
}

Write-Host "Waiting 15s for SIT propagation..." -ForegroundColor Cyan
Start-Sleep -Seconds 15
$allOk = $true
foreach ($sitName in $ExpectedSITs) {
    $sit = Get-DlpSensitiveInformationType -Identity $sitName -ErrorAction SilentlyContinue
    if ($sit) { Write-Host "  [OK]  $sitName" -ForegroundColor Green }
    else { Write-Host "  [MISSING]  $sitName (may still propagate)" -ForegroundColor Yellow; $allOk = $false }
}
if ($allOk) { Write-Host "All ${customNonBuiltIn.length} SITs verified. Ready for Script 2." -ForegroundColor Green }
else { Write-Host "Some SITs not visible yet — wait 2-5 min then re-verify." -ForegroundColor Yellow }`
}

// ── Script 2: DLP policy deployment ─────────────────────────────────────────

export function buildScript2(allSITs, selectedSITIds, selectedPolicyIds, policyConfigs, policyExtraSITs = {}, adminUPN) {
  const policies = POLICIES.filter(p => selectedPolicyIds.has(p.id))
  const locMap = { Exchange:'ExchangeLocation', SharePoint:'SharePointLocation', OneDrive:'OneDriveLocation', Teams:'TeamsLocation' }
  const needsEndpoint = policies.some(p => p.endpointOnly)
  const upn = adminUPN?.trim() || 'admin@yourtenant.onmicrosoft.com'

  // Collect SITs per group including extras added via picker
  function collectGroupSITs(group) {
    const seen = new Set(); const result = []
    policies.filter(p => p.group === group).forEach(p => {
      getEffectiveSITsForPolicy(p, allSITs, selectedSITIds, policyExtraSITs).forEach(s => {
        if (!seen.has(s.guid)) { seen.add(s.guid); result.push(s) }
      })
    })
    return result
  }
  const finSITs = collectGroupSITs('financial')
  const piiSITs = collectGroupSITs('pii')

  const L = []

  L.push(`#Requires -Modules ExchangeOnlineManagement`)
  L.push(`#------------------------------------------------------------------------------`)
  L.push(`# Script 2 of 2: Deploy SA Custom DLP Policies`)
  L.push(`# Generated by: BUI Purview Deployment Script Generator`)
  L.push(`# PREREQUISITES: Script 1 (Custom SITs) must be deployed and verified first.`)
  L.push(`# POLICIES (${policies.length}): ${policies.map(p => policyConfigs[p.id]?.name || p.name).join(' | ')}`)
  L.push(`#------------------------------------------------------------------------------`)
  L.push(`$AdminUPN = "${upn}"`)
  L.push(`Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force`)
  L.push(`if (-not (Get-Module -ListAvailable -Name ExchangeOnlineManagement)) { Install-Module -Name ExchangeOnlineManagement -Force -Scope CurrentUser }`)
  L.push(`Import-Module ExchangeOnlineManagement`)
  L.push(`Connect-IPPSSession -UserPrincipalName $AdminUPN`)
  L.push(``)
  L.push(`function Deploy-DlpRuleWithRetry { param([Parameter(Mandatory)][hashtable]$RuleParams,[int]$MaxRetries=3,[int]$RetryDelaySec=10)`)
  L.push(`    $attempt=0; while($attempt -lt $MaxRetries) { try {`)
  L.push(`        New-DlpComplianceRule @RuleParams -ErrorAction Stop | Out-Null`)
  L.push(`        $v=Get-DlpComplianceRule -Identity $RuleParams.Name -ErrorAction SilentlyContinue`)
  L.push(`        if($v){Write-Host "  [OK]  $($RuleParams.Name)" -ForegroundColor Green;return}`)
  L.push(`        throw "Rule not found after creation."`)
  L.push(`    } catch { $attempt++`)
  L.push(`        if($attempt -lt $MaxRetries){Write-Host "  [RETRY $attempt]  $($RuleParams.Name)" -ForegroundColor Yellow;Start-Sleep -Seconds $RetryDelaySec}`)
  L.push(`        else{Write-Host "  [FAILED]  $($RuleParams.Name) -- $_" -ForegroundColor Red}}}}`);
  L.push(``)

  if (needsEndpoint) {
    L.push(`$epAvail=$false; try{$m=Get-Command New-DlpCompliancePolicy -ErrorAction Stop`)
    L.push(`    if($m.Parameters.ContainsKey("EndpointDlpLocation")){$epAvail=$true;Write-Host "  [OK]  Endpoint DLP available." -ForegroundColor Green}`)
    L.push(`    else{Write-Host "  [SKIP]  Endpoint DLP requires E5/Purview Suite." -ForegroundColor Yellow}`)
    L.push(`}catch{Write-Host "  [SKIP]  $_" -ForegroundColor Yellow}`)
    L.push(``)
  }

  L.push(`function New-PolicyIfNotExists { param([string]$Name,[scriptblock]$CB)`)
  L.push(`    if(Get-DlpCompliancePolicy -Identity $Name -ErrorAction SilentlyContinue){Write-Host "  [EXISTS]  $Name" -ForegroundColor Yellow}`)
  L.push(`    else{try{& $CB;Write-Host "  [OK]  $Name" -ForegroundColor Green}catch{Write-Host "  [FAILED]  $Name -- $_" -ForegroundColor Red}}}`)
  L.push(``)

  policies.forEach(p => {
    const cfg = policyConfigs[p.id] || { name: p.name, mode: 'TestWithoutNotifications', locs: p.locs }
    const comment = p.group === 'financial'
      ? 'Detects SA financial data shared externally.'
      : 'Detects SA PII shared externally.'
    if (p.endpointOnly) {
      L.push(`if($epAvail){New-PolicyIfNotExists "${cfg.name}" { New-DlpCompliancePolicy -Name "${cfg.name}" -Comment "${comment}" -EndpointDlpLocation "All" -Mode "${cfg.mode}" -ErrorAction Stop | Out-Null }}`)
      L.push(`else{Write-Host "  [SKIP]  ${cfg.name}" -ForegroundColor Yellow}`)
    } else {
      const lp = (cfg.locs || p.locs).filter(l => locMap[l]).map(l => `-${locMap[l]} "All"`).join(' ')
      L.push(`New-PolicyIfNotExists "${cfg.name}" { New-DlpCompliancePolicy -Name "${cfg.name}" -Comment "${comment}" ${lp} -Mode "${cfg.mode}" -ErrorAction Stop | Out-Null }`)
    }
  })
  L.push(`Write-Host "Waiting 30s..." -ForegroundColor Cyan; Start-Sleep -Seconds 30`)
  L.push(``)

  // JSON rule blocks
  const uniqueGroups = [...new Set(policies.map(p => p.group + (p.endpointOnly ? '_dev' : '')))]
  uniqueGroups.forEach(grpKey => {
    const isDevice = grpKey.endsWith('_dev')
    const grp = grpKey.replace('_dev', '')
    const sitList = grp === 'financial' ? finSITs : piiSITs
    const repPolicy = policies.find(p => p.group === grp && !!p.endpointOnly === isDevice)
    if (!repPolicy || sitList.length === 0) return
    const cfg = policyConfigs[repPolicy.id] || { lowMin: 1, lowMax: 9, highMin: 10 }
    const varSuffix = grp === 'financial' ? (isDevice ? 'FinDev' : 'Fin') : (isDevice ? 'PiiDev' : 'Pii')
    const grpLabel = grp === 'financial' ? 'Financial' : 'PII'
    const lowLines  = sitList.map(s => `              { "Name": "${s.name}", "Id": "${s.guid}", "Mincount": ${cfg.lowMin || 1},  "Maxcount": ${cfg.lowMax || 9}, "Confidencelevel": "${s.conf}" }`).join(',\n')
    const highLines = sitList.map(s => `              { "Name": "${s.name}", "Id": "${s.guid}", "Mincount": ${cfg.highMin || 10}, "Maxcount": -1, "Confidencelevel": "${s.conf}" }`).join(',\n')

    ;[`$${varSuffix}LowJson`, `$${varSuffix}HighJson`].forEach((vn, idx) => {
      const lines = idx === 0 ? lowLines : highLines
      L.push(`${vn} = @"`)
      L.push(`{ "Version": "1.0", "Condition": { "Operator": "And", "SubConditions": [`)
      L.push(`  { "ConditionName": "ContentContainsSensitiveInformation",`)
      L.push(`    "Value": [{ "Groups": [{ "Name": "SA ${grpLabel} SITs", "Operator": "Or", "Sensitivetypes": [`)
      L.push(lines)
      if (isDevice) {
        L.push(`  ]}]}] }`)
        L.push(`] } }`)
      } else {
        L.push(`  ]}]}] },`)
        L.push(`  { "ConditionName": "AccessScope", "Value": "NotInOrganization" }`)
        L.push(`] } }`)
      }
      L.push(`"@`)
      L.push(``)
    })
  })

  const finPolicies = policies.filter(p => p.group === 'financial' && !p.endpointOnly)
  const piiPolicies = policies.filter(p => p.group === 'pii' && !p.endpointOnly)
  if (finPolicies.length > 0) L.push(`$tipFin = "${(policyConfigs[finPolicies[0].id]?.tipText || '').replace(/"/g, "'")}"`)
  if (piiPolicies.length > 0) L.push(`$tipPII = "${(policyConfigs[piiPolicies[0].id]?.tipText || '').replace(/"/g, "'")}"`)
  L.push(``)

  policies.forEach(p => {
    const cfg = policyConfigs[p.id] || { name: p.name }
    const isDevice = !!p.endpointOnly
    const varSuffix = p.group === 'financial' ? (isDevice ? 'FinDev' : 'Fin') : (isDevice ? 'PiiDev' : 'Pii')
    const tipVar = p.group === 'financial' ? '$tipFin' : '$tipPII'
    const tipOpt = (cfg.locs || p.locs).includes('Exchange') ? 'Dialog' : 'Tip'
    if (isDevice) {
      L.push(`if($epAvail){`)
      L.push(`    Deploy-DlpRuleWithRetry @{Name="Low Vol - ${cfg.name}";Policy="${cfg.name}";AdvancedRule=$${varSuffix}LowJson;GenerateAlert=@();NotifyUser=@();StopPolicyProcessing=$false}`)
      L.push(`    Deploy-DlpRuleWithRetry @{Name="High Vol - ${cfg.name}";Policy="${cfg.name}";AdvancedRule=$${varSuffix}HighJson;GenerateAlert=@("True");NotifyUser=@();ReportSeverityLevel="Medium";StopPolicyProcessing=$false}`)
      L.push(`}else{Write-Host "  [SKIP]  ${cfg.name} rules" -ForegroundColor Yellow}`)
    } else {
      L.push(`Deploy-DlpRuleWithRetry @{Name="Low Vol - ${cfg.name}";Policy="${cfg.name}";AdvancedRule=$${varSuffix}LowJson;GenerateAlert=@();NotifyUser=@();StopPolicyProcessing=$false}`)
      L.push(`Deploy-DlpRuleWithRetry @{Name="High Vol - ${cfg.name}";Policy="${cfg.name}";AdvancedRule=$${varSuffix}HighJson;GenerateAlert=@("True");NotifyUser=@("LastModifier");NotifyUserType="PolicyTip";NotifyPolicyTipCustomText=${tipVar};NotifyPolicyTipDisplayOption="${tipOpt}";ReportSeverityLevel="Medium";StopPolicyProcessing=$false}`)
    }
    L.push(``)
  })

  L.push(`Write-Host "========================================" -ForegroundColor Cyan`)
  L.push(`Write-Host " Deployment complete. Review match data before activating." -ForegroundColor Green`)
  L.push(`Write-Host "========================================" -ForegroundColor Cyan`)

  return L.join('\n')
}
